# Generated by Django 5.2.11 on 2026-02-15 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencies', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeCycleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualitative_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('quantitative_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('qual_tercile', models.PositiveSmallIntegerField(default=1)),
                ('quant_tercile', models.PositiveSmallIntegerField(default=1)),
                ('box_code', models.CharField(default='', max_length=32)),
                ('box_label', models.CharField(default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_scores', to='people.employee')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_scores', to='evaluations.evaluationcycle')),
            ],
            options={
                'indexes': [models.Index(fields=['cycle', 'box_code'], name='evaluations_cycle_i_94938f_idx'), models.Index(fields=['cycle', 'qualitative_score'], name='evaluations_cycle_i_8e76ae_idx'), models.Index(fields=['cycle', 'quantitative_score'], name='evaluations_cycle_i_ad4664_idx')],
                'unique_together': {('employee', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='QualitativeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weight_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('completion_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_qual_goals', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qual_goals', to='evaluations.evaluationcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qual_goals', to='people.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'cycle'], name='evaluations_employe_0cb250_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuantitativeIndicatorAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('met', models.BooleanField(default=False)),
                ('assessed_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessed_indicators', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quant_assessments', to='evaluations.evaluationcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quant_assessments', to='people.employee')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='competencies.levelindicator')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'cycle'], name='evaluations_employe_cac6e6_idx')],
                'unique_together': {('employee', 'cycle', 'indicator')},
            },
        ),
    ]
