# Generated by Django 5.2.12 on 2026-04-04 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competencies", "0001_initial"),
        ("evaluations", "0002_swap_axes_and_qualitative_ratings"),
        ("people", "0004_merge_20260215_2243"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualitativeIndicatorSelfAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Nunca"),
                            (2, "Casi nunca"),
                            (3, "Casi siempre"),
                            (4, "Siempre"),
                        ],
                        default=1,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuantitativeGoalSelfAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completion_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="qualitativeindicatorassessment",
            new_name="evaluations_employe_3b156c_idx",
            old_name="evaluations_employe_cac6e6_idx",
        ),
        migrations.RenameIndex(
            model_name="quantitativegoal",
            new_name="evaluations_employe_2a67aa_idx",
            old_name="evaluations_employe_0cb250_idx",
        ),
        migrations.AlterField(
            model_name="qualitativeindicatorassessment",
            name="assessed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessed_behaviors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="qualitativeindicatorassessment",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qual_assessments",
                to="evaluations.evaluationcycle",
            ),
        ),
        migrations.AlterField(
            model_name="qualitativeindicatorassessment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qual_assessments",
                to="people.employee",
            ),
        ),
        migrations.AlterField(
            model_name="quantitativegoal",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_quant_goals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quantitativegoal",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quant_goals",
                to="evaluations.evaluationcycle",
            ),
        ),
        migrations.AlterField(
            model_name="quantitativegoal",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quant_goals",
                to="people.employee",
            ),
        ),
        migrations.AddField(
            model_name="qualitativeindicatorselfassessment",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qual_self_assessments",
                to="evaluations.evaluationcycle",
            ),
        ),
        migrations.AddField(
            model_name="qualitativeindicatorselfassessment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qual_self_assessments",
                to="people.employee",
            ),
        ),
        migrations.AddField(
            model_name="qualitativeindicatorselfassessment",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="self_assessments",
                to="competencies.levelindicator",
            ),
        ),
        migrations.AddField(
            model_name="quantitativegoalselfassessment",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quant_self_assessments",
                to="evaluations.evaluationcycle",
            ),
        ),
        migrations.AddField(
            model_name="quantitativegoalselfassessment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quant_self_assessments",
                to="people.employee",
            ),
        ),
        migrations.AddField(
            model_name="quantitativegoalselfassessment",
            name="goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="self_assessments",
                to="evaluations.quantitativegoal",
            ),
        ),
        migrations.AddIndex(
            model_name="qualitativeindicatorselfassessment",
            index=models.Index(
                fields=["employee", "cycle"], name="evaluations_employe_549994_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="qualitativeindicatorselfassessment",
            unique_together={("employee", "cycle", "indicator")},
        ),
        migrations.AddIndex(
            model_name="quantitativegoalselfassessment",
            index=models.Index(
                fields=["employee", "cycle"], name="evaluations_employe_f8526b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quantitativegoalselfassessment",
            unique_together={("employee", "cycle", "goal")},
        ),
    ]
