# Generated by Django 5.2.11 on 2026-02-25 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competencies", "0001_initial"),
        ("evaluations", "0002_swap_axes_and_qualitative_ratings"),
        ("people", "0005_invitation_employee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="qualitativeindicatorassessment",
            new_name="evaluations_employe_3b156c_idx",
            old_name="evaluations_employe_cac6e6_idx",
        ),
        migrations.RenameIndex(
            model_name="quantitativegoal",
            new_name="evaluations_employe_2a67aa_idx",
            old_name="evaluations_employe_0cb250_idx",
        ),
        migrations.AlterUniqueTogether(
            name="qualitativeindicatorassessment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="qualitativeindicatorassessment",
            name="assessment_type",
            field=models.CharField(
                choices=[("manager", "Manager"), ("self", "Autoevaluación")],
                default="manager",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="qualitativeindicatorassessment",
            name="assessed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessed_behaviors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="qualitativeindicatorassessment",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qual_assessments",
                to="evaluations.evaluationcycle",
            ),
        ),
        migrations.AlterField(
            model_name="qualitativeindicatorassessment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qual_assessments",
                to="people.employee",
            ),
        ),
        migrations.AlterField(
            model_name="quantitativegoal",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_quant_goals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quantitativegoal",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quant_goals",
                to="evaluations.evaluationcycle",
            ),
        ),
        migrations.AlterField(
            model_name="quantitativegoal",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quant_goals",
                to="people.employee",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="qualitativeindicatorassessment",
            unique_together={("employee", "cycle", "indicator", "assessment_type")},
        ),
    ]
