# Generated by Django 5.2.12 on 2026-04-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0003_qualitativeindicatorselfassessment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TalentMapSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualitative_axis_method",
                    models.CharField(
                        choices=[
                            ("THIRDS", "Tercios por reglas del perfil ideal"),
                            ("GAUSSIAN", "Campana de Gauss (por score cualitativo)"),
                        ],
                        default="THIRDS",
                        max_length=20,
                    ),
                ),
                ("top_min_above", models.PositiveSmallIntegerField(default=1)),
                ("middle_max_below", models.PositiveSmallIntegerField(default=3)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
