# Generated by Django 5.2.11 on 2026-02-15 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetencyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=160)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='competencies.competency')),
            ],
            options={
                'ordering': ['competency__name', 'level'],
                'unique_together': {('competency', 'level')},
            },
        ),
        migrations.CreateModel(
            name='LevelIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='competencies.competencylevel')),
            ],
            options={
                'ordering': ['level__competency__name', 'level__level', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoleCompetencyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.PositiveIntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_requirements', to='competencies.competency')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_requirements', to='people.role')),
            ],
            options={
                'unique_together': {('role', 'competency')},
            },
        ),
    ]
