# Generated by Django 5.2.11 on 2026-02-15 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_add_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
