# Generated by Django 5.2.11 on 2026-02-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_invitation_created_at'),
        ('people', '0003_invitation_manager'),
    ]

    operations = [
    ]
