# Generated by Django 5.2.12 on 2026-04-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_merge_20260215_2243"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(default="TalentMap", max_length=120)),
                ("primary_color", models.CharField(default="#2563eb", max_length=7)),
                ("header_background_url", models.URLField(blank=True, default="")),
                ("login_background_url", models.URLField(blank=True, default="")),
                ("card_glass_effect", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
