# Generated by Django 5.2.11 on 2026-02-25 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_merge_20260215_2243"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_invitations",
                to="people.employee",
            ),
        ),
    ]
